### ISSUE TITLE
Is tools_additional_repo pointing to the right repos ?

### ISSUE THREAD

**Issue by Bischoff** [uyuni-project/sumaform#722]
In `salt/repos/default.sls`:
```
{% if 'nightly' in grains.get('product_version') | default('', true) %}
tools_additional_repo:
  pkgrepo.managed:
  - baseurl: http://{{ grains.get("mirror") | default("download.suse.de", true) }}/ibs/Devel:/Galaxy:/Manager:/4.0:/SLE15-SUSE-Manager-Tools/images/repo/SLE-15-Manager-Tools-POOL-x86_64-Media1/
  - priority: 98
```

(please note `4.0` in the URL)

but according to @juliogonzalez "it should be using Head".

I have no idea why this would be wrong, to be clarified with Julio.
